services:
  - type: web
    name: flask-server
    runtime: python
    buildCommand: "poetry install"
    startCommand: "gunicorn server.app:app"
    envVars:
      - key: SECRET_KEY
        value: 8N3F2FmsdGnT7E0QrW-Jd9S8Sy3Q3mZ04RtTYgVwF6z3lzOiNH3CKTUKFeNdqFPO
    region: oregon
    plan: free
