"""reset

Revision ID: 64df8490136a
Revises: 
Create Date: 2025-07-29 01:25:46.552722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64df8490136a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_option_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'meal_options', ['meal_option_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('meal_option_id')

    # ### end Alembic commands ###
