"""Add caterer_id foreign key to Order

Revision ID: 850980eebbca
Revises: 7a5534cd0f40
Create Date: 2025-07-19 07:50:51.279962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850980eebbca'
down_revision = '7a5534cd0f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caterer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'caterers', ['caterer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('caterer_id')

    # ### end Alembic commands ###
