"""Add caterer_id to menu table

Revision ID: fefec9d79495
Revises: f0a073883e7f
Create Date: 2025-07-23 11:01:12.095458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefec9d79495'
down_revision = 'f0a073883e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caterer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'caterers', ['caterer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('caterer_id')

    # ### end Alembic commands ###
